CC=arm-arago-linux-gnueabi-

target:
	$(CC)gcc -O3 -o gpio_test gpio_test.c
	$(CC)gcc -O3 -o gpio_test2 gpio_test2.c
	$(CC)gcc -O3 -o sysfs_gpio sysfs_gpio.c
clean:
	@rm -vf gpio_test sysfs_gpio gpio_test2

