#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.C674{1,0,7.4,1
#
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/app_p674.o674.dep
endif

package/cfg/app_p674.o674: | .interfaces
package/cfg/app_p674.o674: package/cfg/app_p674.c package/cfg/app_p674.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cl674 $< ...
	$(ti.targets.C674.rootDir)/bin/cl6x -c  -g --optimize_with_debug -qq -pdsw225 -mo --no_compress -mv6740 -eo.o674 -ea.s674  --embed_inline_assembly  -Dxdc_cfg__header__='xconfig_app/package/cfg/app_p674.h'  -Dxdc_target_name__=C674 -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_7_4_1 -O2  $(XDCINCS) -I$(ti.targets.C674.rootDir)/include -fs=./package/cfg -fr=./package/cfg -fc $<
	$(MKDEP) -a $@.dep -p package/cfg -s o674 $< -C   -g --optimize_with_debug -qq -pdsw225 -mo --no_compress -mv6740 -eo.o674 -ea.s674  --embed_inline_assembly  -Dxdc_cfg__header__='xconfig_app/package/cfg/app_p674.h'  -Dxdc_target_name__=C674 -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_7_4_1 -O2  $(XDCINCS) -I$(ti.targets.C674.rootDir)/include -fs=./package/cfg -fr=./package/cfg
	-@$(FIXDEP) $@.dep $@.dep
	
package/cfg/app_p674.o674: export C_DIR=
package/cfg/app_p674.o674: PATH:=$(ti.targets.C674.rootDir)/bin/;$(PATH)
package/cfg/app_p674.o674: Path:=$(ti.targets.C674.rootDir)/bin/;$(PATH)

package/cfg/app_p674.s674: | .interfaces
package/cfg/app_p674.s674: package/cfg/app_p674.c package/cfg/app_p674.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cl674 -n $< ...
	$(ti.targets.C674.rootDir)/bin/cl6x -c -n -s --symdebug:none -g --optimize_with_debug -qq -pdsw225 -mv6740 -eo.o674 -ea.s674   -Dxdc_cfg__header__='xconfig_app/package/cfg/app_p674.h'  -Dxdc_target_name__=C674 -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_7_4_1 -O2  $(XDCINCS) -I$(ti.targets.C674.rootDir)/include -fs=./package/cfg -fr=./package/cfg -fc $<
	$(MKDEP) -a $@.dep -p package/cfg -s o674 $< -C  -n -s --symdebug:none -g --optimize_with_debug -qq -pdsw225 -mv6740 -eo.o674 -ea.s674   -Dxdc_cfg__header__='xconfig_app/package/cfg/app_p674.h'  -Dxdc_target_name__=C674 -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_7_4_1 -O2  $(XDCINCS) -I$(ti.targets.C674.rootDir)/include -fs=./package/cfg -fr=./package/cfg
	-@$(FIXDEP) $@.dep $@.dep
	
package/cfg/app_p674.s674: export C_DIR=
package/cfg/app_p674.s674: PATH:=$(ti.targets.C674.rootDir)/bin/;$(PATH)
package/cfg/app_p674.s674: Path:=$(ti.targets.C674.rootDir)/bin/;$(PATH)

clean,674 ::
	-$(RM) package/cfg/app_p674.o674
	-$(RM) package/cfg/app_p674.s674

app.p674: package/cfg/app_p674.o674 package/cfg/app_p674.mak

clean::
	-$(RM) package/cfg/app_p674.mak
