/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      300,                                       
            catalogName:    "ti.catalog.c6000",
            deviceName:     "OMAPL138",
            customMemoryMap:
           [          
                ["IRAM", 
                     {
                        name: "IRAM",
                        base: 0x11800000,                    
                        len: 0x00018000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["IROM", 
                     {
                        name: "IROM",
                        base: 0x11700000,                    
                        len: 0x00100000,                    
                        space: "code/data",
                        access: "RX",
                     }
                ],
                ["L1DSRAM", 
                     {
                        name: "L1DSRAM",
                        base: 0x11F00000,                    
                        len: 0x00008000,                    
                        space: "data",
                        access: "RW",
                     }
                ],
                ["L1PSRAM", 
                     {
                        name: "L1PSRAM",
                        base: 0x11E00000,                    
                        len: 0x00008000,                    
                        space: "code",
                        access: "RWX",
                     }
                ],
                ["L3_CBA_RAM", 
                     {
                        name: "L3_CBA_RAM",
                        base: 0x80002800,                    
                        len: 0x0001D800,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["SR_0", 
                     {
                        name: "SR_0",
                        base: 0xC2000000,                    
                        len: 0x00010000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["SR_1", 
                     {
                        name: "SR_1",
                        base: 0xC2010000,                    
                        len: 0x00FF0000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DSP_PROG", 
                     {
                        name: "DSP_PROG",
                        base: 0xC3000000,                    
                        len: 0x00800000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["APPDRAM", 
                     {
                        name: "APPDRAM",
                        base: 0x11818000,                    
                        len: 0x00028000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
           ],
          l2Mode:"0k",
          l1PMode:"0k",
          l1DMode:"0k",

    });
    
instance :
    
    override config string codeMemory  = "DSP_PROG";   
    override config string dataMemory  = "APPDRAM";                                
    override config string stackMemory = "IRAM";
    
}
