#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.elf.C674{1,0,7.4,1
#
Dsp1.xe674: package/cfg/Dsp1.xe674.mak

clean::
	-$(RM) package/cfg/Dsp1.xe674.mak
